### ISSUE TITLE
Should this be in Typescript?

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/beautifier-prettydiff#1]

**Comment by Glavin001** [comment]
I would like it to be written in TypeScript, like https://github.com/Unibeautify/beautifier-prettier .

**Comment by szeck87** [comment]
I started a branch and started changes: https://github.com/Unibeautify/beautifier-prettydiff/tree/migrate-to-typescript

Some and languages and the ternaryline option need to be added to unibeautify though

**Comment by Glavin001** [comment]
I added some comments to https://github.com/Unibeautify/beautifier-prettydiff/commit/611935676a875f138aac597557b8b449845ce7b6
Great work so far!

**Comment by szeck87** [comment]
Completed in #2.
